{
 "title": "Cron Jobs",
 "description": "A simple dashboard to monitor k8s Cron Jobs ",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "cronjob",
    "query": {
     "query": "label_values(kube_cronjob_info{namespace=\"$namespace\"}, cronjob)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cron Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Number of Cron Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_cronjob_info{namespace=\"$namespace\"})  or vector(0)"
    }
   ]
  },
  {
   "title": "Suspended Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time((kube_cronjob_spec_suspend{namespace=\"$namespace\"} > 0)[$__range:])) or vector(0)"
    }
   ]
  },
  {
   "title": "Active Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max by(job_name, namespace, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"}) and on(job_name, namespace) kube_job_status_active) or vector(0)"
    }
   ]
  },
  {
   "title": "Failed Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max_over_time((max by (owner_name) (kube_job_failed{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"})) > 0)[$__range:])) or vector(0)"
    }
   ]
  },
  {
   "title": "Succeeded Jobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(max_over_time((max by (owner_name) (kube_job_status_succeeded{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"})) > 0)[$__range:])) or vector(0)"
    }
   ]
  },
  {
   "title": "Cron Jobs Status",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(max_over_time((max by (owner_name) (kube_job_failed{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"})) > 0)[$__range:])) or vector(0)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    },
    {
     "expr": "count(max_over_time((max by (owner_name) (kube_job_status_succeeded{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"})) > 0)[$__range:])) or vector(0)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    },
    {
     "expr": "sum(max by(job_name, namespace, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\"}) and on(job_name, namespace) kube_job_status_active) or vector(0)",
     "legendFormat": "{{﻿label_cronjob_owner}}"
    },
    {
     "expr": "count(max_over_time((kube_cronjob_spec_suspend{namespace=\"$namespace\"} > 0)[$__range:])) or vector(0)"
    }
   ]
  },
  {
   "title": "CronJob Summary",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_cronjob_info{namespace=\"$namespace\", cronjob=~\"$cronjob\"}"
    },
    {
     "expr": "max by (cronjob) (kube_cronjob_next_schedule_time{namespace=\"$namespace\", cronjob=~\"$cronjob\"}) * 1000"
    },
    {
     "expr": "max by (cronjob) (kube_cronjob_status_last_schedule_time{namespace=\"$namespace\", cronjob=~\"$cronjob\"}) * 1000"
    },
    {
     "expr": "label_replace(sum by (owner_name) (kube_job_status_active{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})) or vector(0), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(max by (owner_name) (kube_job_failed{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})) or vector(0), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(max by (owner_name) (kube_job_status_succeeded{namespace=\"$namespace\"} * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})) or vector(0), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(max by (owner_name) (max by(job_name, owner_name) ((kube_job_status_completion_time{namespace=\"$namespace\"} - on (job_name) kube_job_created{namespace=\"$namespace\"}) * on (job_name) kube_job_status_succeeded{namespace=\"$namespace\"}) * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(min by (owner_name) (min by(job_name, owner_name) ((kube_job_status_completion_time{namespace=\"$namespace\"} - on (job_name) kube_job_created{namespace=\"$namespace\"}) * on (job_name) kube_job_status_succeeded{namespace=\"$namespace\"}) * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    },
    {
     "expr": "label_replace(avg by (owner_name) (max by(job_name, owner_name) ((kube_job_status_completion_time{namespace=\"$namespace\"} - on (job_name) kube_job_created{namespace=\"$namespace\"}) * on (job_name) kube_job_status_succeeded{namespace=\"$namespace\"}) * on (job_name) group_left(owner_name) max by(job_name, owner_name, owner_kind) (kube_job_owner{owner_kind=\"CronJob\", namespace=\"$namespace\", owner_name=~\"$cronjob\"})), \"cronjob\", \"$1\", \"owner_name\", \"(.*)\")"
    }
   ]
  }
 ]
}