{
 "title": "Kubernetes / Autoscaling / Keda / Scaled Object",
 "description": "A dashboard that monitors Keda and focuses on giving a overview for Scaled Objects. It is created using the [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
 "tags": [
  "kubernetes",
  "autoscaling",
  "kubernetes-autoscaling-mixin",
  "keda"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(keda_scaled_object_paused{}, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\"}, job)"
   },
   {
    "name": "operator_namespace",
    "label": "Operator Namespace",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\"}, namespace)"
   },
   {
    "name": "resource_namespace",
    "label": "Resource Namespace",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\"}, exported_namespace)"
   },
   {
    "name": "scaled_object",
    "label": "Scaled Object",
    "query": "label_values(keda_scaled_object_paused{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=~\"$resource_namespace\"}, scaledObject)"
   },
   {
    "name": "scaler",
    "label": "Scaler",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", scaledObject=\"$scaled_object\"}, scaler)"
   },
   {
    "name": "metric",
    "label": "Metric",
    "query": "label_values(keda_scaler_active{cluster=\"$cluster\", job=~\"$job\", namespace=~\"$operator_namespace\", exported_namespace=\"$resource_namespace\", scaledObject=~\"$scaled_object\", scaler=~\"$scaler\"}, metric)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resources Registered by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_resource_registered_total{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\",\n    type=\"scaled_object\"\n  }\n) by (exported_namespace, type)\n",
     "legendFormat": "{{ exported_namespace }}/{{ type }}"
    }
   ]
  },
  {
   "title": "Triggers by Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_trigger_registered_total{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\",\n  }\n) by (type)\n",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Scaled Objects Paused",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaled_object_paused{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    scaledObject=\"$scaled_object\"\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Objects Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaled_object_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=~\"$operator_namespace\",\n      exported_namespace=~\"$resource_namespace\",\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaler Detail Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=~\"$operator_namespace\",\n      exported_namespace=~\"$resource_namespace\",\n      type=\"scaledobject\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject, scaler)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }}"
    }
   ]
  },
  {
   "title": "Scale Target Values",
   "type": "table",
   "description": "This table has links to the HPA for the scaled object, which can be used to see the current scaling status and history. The HPA dashboard can be found at [kubernetes-autoscaling-mixin](https://github.com/adinhodovic/kubernetes-autoscaling-mixin).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=~\"$operator_namespace\",\n    exported_namespace=~\"$resource_namespace\",\n    type=\"scaledobject\"\n  }\n) by (job, exported_namespace, scaledObject, scaler, metric)\n"
    }
   ]
  },
  {
   "title": "Scaled Object $scaled_object / $scaler / $metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Scaled Object Paused",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaled_object_paused{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    scaledObject=\"$scaled_object\"\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Active",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  keda_scaler_active{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledobject\",\n    scaledObject=\"$scaled_object\"\n  }\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Detail Errors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n  increase(\n    keda_scaler_detail_errors_total{\n      cluster=\"$cluster\",\n      job=~\"$job\",\n      namespace=\"$operator_namespace\",\n      exported_namespace=\"$resource_namespace\",\n      type=\"scaledobject\",\n      scaledObject=\"$scaled_object\"\n    }[$__rate_interval]\n  )\n) by (exported_namespace, scaledObject)\n",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  {
   "title": "Scaled Object Metric Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_value{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledobject\",\n    scaledObject=\"$scaled_object\",\n    scaler=\"$scaler\",\n    metric=\"$metric\"\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  },
  {
   "title": "Scaled Object Metric Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  keda_scaler_metrics_latency_seconds{\n    cluster=\"$cluster\",\n    job=~\"$job\",\n    namespace=\"$operator_namespace\",\n    exported_namespace=\"$resource_namespace\",\n    type=\"scaledobject\",\n    scaledObject=\"$scaled_object\",\n    scaler=\"$scaler\",\n    metric=\"$metric\"\n  }\n) by (exported_namespace, scaledObject, scaler, metric)\n",
     "legendFormat": "{{ scaledObject }} / {{ scaler }} / {{ metric }}"
    }
   ]
  }
 ]
}